### ISSUE TITLE
Is it possible to add a button on the admin abandoned carts, that manually sends an email?

### ISSUE THREAD

**Issue by localhosted** [vpietri/ADM_AbandonedCart#1]
Most abandoned carts plugins are all set to send emails on a timer, but not all abandoned carts are worth pursuing, or even actual abandoned carts (magento sometimes leaves carts as "abandoned", even if the same client made a purchase in the same day).

Is it possible to manually trigger an email while on the abandoned carts grid?

**Comment by vpietri** [comment]
> magento sometimes leaves carts as "abandoned", even if the same client made a purchase in the same day

Don't think Magento leaves several quotes as is_active for a same customer

**Comment by vpietri** [comment]
Will see if I can add a button in the grid. I have other enhancement to do for this extension.

**Comment by vpietri** [comment]
@localhosted : Mass action is added in admin grid to send emails

**Comment by localhosted** [comment]
Thanks! This will solve a big issue.
